### ISSUE TITLE
Imagery/Basemap

### ISSUE THREAD

**Issue by woswald** [agrc/daq-web-framework#27]
The changes that we made to the basemaps last week, seems to cause some strange behavior in Collector, where the layers aren't drawing on the new basemap that was added.  It think the additional white tiles (see image) are causing some of the issues.  If I switch the basemap in Collector to a different basemap it seems to resolve the issue.  Is there an alternative we can use to have both imagery and streets in the map?

Seen in http://test.mapserv.utah.gov/daq/:
![image](https://cloud.githubusercontent.com/assets/7386943/23415543/b71ed3ba-fd9c-11e6-83bd-ecb4edc20d5c.png)

Seen in Collector:

**Comment by steveoh** [comment]
I can't see the collector links since they are links to your email. I edited your comment just in case there was a security risk of those being there.

Thanks for testing this web map with the discover services though. I think since it's not working as expected you should create a separate map for collector. We can continue to use the discover.agrc.utah.gov services in the app if you so choose. For the collector web map, I would recommend using the esri `world imagery`, `world transporation`, and `world boundaries and places` layers.

**Comment by woswald** [comment]
@steveoh 

Sorry, these are the Collector links:
![screenshot_2017-02-28-10-01-59](https://cloud.githubusercontent.com/assets/7386943/23467936/98a9f318-fe5c-11e6-892f-2489f877ae8b.png)
![screenshot_2017-02-28-10-02-23](https://cloud.githubusercontent.com/assets/7386943/23467935/98150d98-fe5c-11e6-897c-0cd55f129696.png)
![screenshot_2017-02-28-10-01-12](https://cloud.githubusercontent.com/assets/7386943/23467932/976d0e7c-fe5c-11e6-9919-a201c9c06e3c.png)

If we have a separate map for Collector, will the attachments still be present in Collector? I thought the common map id is why that works.

**Comment by steveoh** [comment]
Yes the attachments are on the facility feature service so as long as you include that as well the attachments will also be present.

**Comment by brigsz** [comment]
@woswald @steveoh Are we not better off with the .tpk files?  For people licensed for the google imagery, such as DAQ couldn't we just create .tpk files for them as a "hybrid basemap"?
