### ISSUE TITLE
Add AI Number Not Working

### ISSUE THREAD

**Issue by woswald** [agrc/daq-web-framework#32]
### Steps to reproduce
1. Click on a 2014 O&G Facilities point on the map.
2. Once the Item Information is showing, and you can see that it does not have an AI #, and can also see that the Add AI Number tool is showing.
3. Enter the AI# 10791 into the AI number field of the Add AI Number tool, and click Add AI Number.
4. Add AI Number tool disappears, but no AI # appears in the AI # field of the Feature Information window.
5. Click on the EDoc Items tab.
6. Documents now appear.
7. Click add next to a document to attach the document, however, an error message "error, try again?" is received.

### Expected behaviour
Once an AI number is entered using the AI# tool, the AI # field in the Feature Information window should change to the entered AI #. This should be retained with the feature layer indefinitely (unless edited) as well. In the EDoc Items tab, once add is clicked next to a document, the document should attach, a success message should be received.

### Actual behaviour
After entering an AI# the add AI Number tool disappears, but no AI # appears in the AI # field in the Feature Information window. 
Also, the add document feature returns an error message instead of attaching a document.

**Comment by woswald** [comment]
After waiting a while and re-clicking on the point, it seems that the AI# does eventually add. It just seems to be very delayed. I am still unable to attach a document, however, this is probably a separate issue from the AI number adding issue.

**Comment by steveoh** [comment]
> Add AI Number tool disappears, but no AI # appears in the AI # field of the Feature Information window.

The ai number is not reflected in the attributes because the feature layer, when fetched from arcgis online, had the unedited data. The feature needs to be refreshed from the server to get the updated attribute data. 

I will update the attribute table when the ai number is successfully edited, show the grid panel, and try to update the feature layer data for the feature that was updated so if clicked on again it will show the newly added ai number.
