### ISSUE TITLE
Attachments Tab - Issues with Image Attachments

### ISSUE THREAD

**Issue by woswald** [agrc/daq-web-framework#46]
### Steps to reproduce
1. Load https://test.mapserv.utah.gov/daq
2. Navigate to a point of interest (one I know has attachments, one I have made sure to attach a picture to through Collector).
3. Click on point of interest.
4. Click on Attachments tab.
5. I get a loading image (3 progressing dots) as if the page is trying to load the attachments, but this just continually persists.
6. No attachments ever get displayed. (See image below)
![image](https://cloud.githubusercontent.com/assets/7386943/26411178/7b59a6c6-4062-11e7-818e-e5aede5cc424.png)
7. If I go back to Collector and remove the picture from the POI, and then go back to https://test.mapserv.utah.gov/daq and repeat the above process the attachments load correctly. (See Image Below)
![image](https://cloud.githubusercontent.com/assets/7386943/26411091/3a6094e0-4062-11e7-82d8-dc583796b8df.png)

### Expected behaviour
Picture attachments should be able to be attached to a POI via Collector and then viewed through the Attachments tab in https://test.mapserv.utah.gov/daq

### Actual behaviour
Only document attachments are currently accessible through the Attachments tab in https://test.mapserv.utah.gov/daq, and the attachment of pictures seems to break the functionality of the Attachments tab so that it is not displaying attachments.

**Comment by steveoh** [comment]
This app expects the uploads to come from the app. This is how we can do the expiration behavior. The api is failing because it expects a naming convention. I can update that to make it optional, but remember anything you upload from collector will be [deleted nightly](https://github.com/agrc/daq-web-framework/issues/18#issuecomment-288890698).

**Comment by woswald** [comment]
Why nightly? I thought the autodelete was 30 days after being attached from Collector.

**Comment by steveoh** [comment]
It's 30 days when uploaded via the app because the app renames the file to have the date it was uploaded. Anything without that gets removed nightly as we discussed in the linked issue. You could name your files with a date to trick the system but since we do not have control over the file names from collector they are treated as uploaded outside of the app and are removed.

**Comment by woswald** [comment]
Ok, I guess I wasn't aware that Autodelete meant deleted nightly.  I thought it was just automatically deleting them after 30 days.  Would it be difficult to change the autodelete period for files from Collector to 30 days, or at least longer than just nightly?

**Comment by steveoh** [comment]
I suppose we could try to enhance the process and if we notice a file without the naming scheme we download/delete/rename/upload to make it conform.

**Comment by woswald** [comment]
Ok.  I think it would be useful to do.  However, if this is going to be something really complex to accomplish, we can probably get by with the nightly delete for now.  I just know in some instances inspectors are in the field for a couple of days, so they may not have the ability to get those image files put onto their desktop computer before the nightly purge. Maybe we can discuss this a bit further on today's call.

**Comment by steveoh** [comment]
We could run the purge script every 7 days instead of nightly. That is the easiest hack to keep uploads around longer.

**Comment by woswald** [comment]
I think that would work just fine.
